student:
  model_name: resnet

teacher:
  model_name: dinov2_vitg14
  out_dim: 1536

data_transform:
  n_global_crops: 2
  n_local_crops: 8
  global_crops_scale: [0.32, 1.0]
  local_crops_scale: [0.05, 0.32]
  global_crops_size: [224, 224]
  local_crops_size: [224, 224]


data_loader:
  batch_size: 32
  num_workers: 8
  shuffle: true
  collate_fn: collate_data_and_cast

optimizer:
  type: AdamW
  lr: 0.0005

dino_loss:
  weight: 1
  student_temp: 0.1
  teacher_temp: 0.07


train:
  max_epochs: 100
  save_checkpoint_freq: 10
  resume_checkpoint: null


model_wrapper:
  model_type: resnet
  n_patches: 256
  target_feature:
    - res5
  feature_matcher_config:
    out_channels: 1536