student:
  model_name: resnet
  student_key: res5
  pretrained: true
  # checkpoint_path: /home/arda/dinov2/distillation/checkpoints/stdc_encoder.pth
  kwargs:
    depth: 50
    out_features: ['res5']
    freeze_at: 0
    norm_type: BN
##Example for STDC
# kwargs:
#   base_channels: 64
#   layers: [4, 5, 3]
#   block_num: 4
#   block_type: cat
#   use_conv_last: false


teacher:
  model_name: dinov2_vitg14
  teacher_key: feature_map
  out_dim: 1536
  n_patches: 256
  feature_matcher:
    out_channels: 1536
    kernel_size: 1
    stride: 1
    padding: 0
    # activation: ReLU


data_transform:
  n_global_crops: 2
  n_local_crops: 8
  global_crops_scale: [0.32, 1.0]
  local_crops_scale: [0.05, 0.32]
  global_crops_size: [224, 224]
  local_crops_size: [224, 224]




optimizer:
  type: AdamW
  kwargs:
    lr: 0.0001
    betas: [0.9, 0.999]
    weight_decay: 0.05
  scheduler:
    type: CosineAnnealingLR
    kwargs:
      T_max: 30
      eta_min: 0.00001
    monitor: val_loss
    interval: epoch
    frequency: 1

loss:
  alpha: 1.0
  beta: 0.0


train:
  name: resnet50
  max_epochs: 30
  accelerator: gpu
  devices: [0,1]
  num_nodes: 1
  strategy: ddp
  # resume_from_checkpoint: /home/arda/dinov2/distillation/logs/resnet50/distillation/version_58/checkpoints/epoch=26-val_similarity=0.56.ckpt

data_loader:
  data_dir: /storage/disk2/sam_resized
  batch_size: 256
  num_workers: 16
  


feature_matcher:
  out_channels: 1536
  kernel_size: 1
  stride: 1
  padding: 0

checkpoints:
  dirpath: checkpoints
  monitor: val_similarity
  mode: max
  save_top_k: 3

